trigger:
  - main
  - develop

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}: 
    - name: archiveName
      value: "LeadCMS.zip"
    - name: leadCmsUrl
      value: '$(LEADCMS_URL)'
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}: 
    - name: archiveName
      value: "LeadCMS_DEV.zip"
    - name: leadCmsUrl
      value: '$(DEV_LEADCMS_URL)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install --production'

  - script: |
      npm run build
    displayName: 'npm run build'
    env:
      GATSBY_LEADCMS_API_URL: '$(leadCmsUrl)'
      GATSBY_LEADCMS_LANGUAGE: '$(TARGET_LANGUAGE)'

  - script: |
      echo User-agent: \* > robots.txt
      echo Disallow: / >> robots.txt
    workingDirectory: public
    displayName: 'disable indexing via robots.txt'
    condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'main'))

  - script: |
      currentDate=`date`
      echo Build: $(Build.BuildNumber) > build.txt
      echo Date and Time: $currentDate >> build.txt
    workingDirectory: public
    displayName: 'add build.txt'


  - task: ArchiveFiles@2
    displayName: 'Put files into $(archiveName)'
    inputs:
      rootFolderOrFile: 'public'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(archiveName)'
      replaceExistingArchive: true      

  - task: PublishBuildArtifacts@1
    displayName: 'Publish $(archiveName) as build artifact'
    inputs:      
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(archiveName)'
      ArtifactName: 'site'
      publishLocation: 'Container'      
